config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  resources :tags, only: [:new, :create, :index]

  resources :posts do
    resources :comments
  end

  resources :users, only: [:new, :create, :edit, :update, :show]

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

  validates :comment_text, presence: true
  validates :comment_text, length: {minimum: 5}
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user

  has_many :post_tagships
  has_many :tags, through: :post_tagships

  has_many :comments

  # Validation
  validates :topic, presence: true
  validates :post_text, presence: true
  validates :post_text, length: { maximum: 200 }
end

app/models/post_tagship.rb
class PostTagship < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :post_tagships
  has_many :posts, through: :post_tagships

  # Validation
  validates :tag_title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  has_many :comments

  has_secure_password validation: false

  # Validation
  validates :name, presence: true
  validates :name, uniqueness: true
  # Run the validation only when a new record is created
  validates :password, presence: true, on: :create
  validates :password, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # Create comments
  def create
    
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params.require(:comment).permit(:comment_text)) 
    
    # User    
    @comment.user = current_user

    if @comment.save
      redirect_to post_path(@post)
    else
      render 'posts/show' 
    end

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # Show the entire list
  def index
    @posts = Post.all
  end
  # Show the content of a post
  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
  end
  #--------------------------------------------------#
  # Create a post
  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)

    # User
    post.user = current_user

    if post.save!
      redirect_to post_path(post)
    else 
      render :new
    end
  end

  private
  def post_params
    params.require(:post).permit(:topic, :post_text, tag_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(name: params[:name])
    
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  # Show the entire list
  def index
    @tags = Tag.all
  end

  # Create a tag
  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save! 
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def tag_params
    params.require(:tag).permit(:tag_title)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
  params.require(:user).permit(:name, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_navbar.html.erb
<nav class = "navbar navbar-inverse">
  <div class = "container-fluid">
<!-- Navbar header: link to root_path (Main)-->
    <div class = "navbar-header">
      <%= link_to "Main", root_path, :class => 'navbar-brand' %>
    </div>
    <div class = "collapse navbar-collapse" id = "bs-example-navbar-collapse-1">
      <ul class = "nav navbar-nav">
<!-- User action: create new posts -->
        <% if logged_in? %>
          <li><%= link_to "Post Here!", new_post_path %></li>
        <% end %>
      </ul>
<!-- Dropdown -->
      <ul class = "nav navbar-nav navbar-right">  
        <% if logged_in? %>
          <li class = "dropdown">
            <%= link_to "#", class: "dropdown-toggle", "data-toggle" => "dropdown" do %>
            <%= current_user.name %> <span class = "caret"></span>
            <% end %>
<!-- Dropdown menu-->
<!-- User action: view profile / logout -->
            <ul class = "dropdown-menu" >
              <li><%= link_to "History", user_path(current_user) %></li>
              <li role = "separator" class = "divider"></li>
              <li><%= link_to "Log Out", logout_path %></li>
            </ul>
          </li>
<!-- Guest action: register / login -->
        <% else %>
          <li><%= link_to "Register", register_path %></li>
          <li><%= link_to "Log In", login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Post Your Words</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Navbar-->
  <header>
    <%= render "layouts/navbar" %>
  </header>

<!-- Container-->
  <div class = "margin_container">
    <div class = "row">
      <div class = "col-md-12">  
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/posts/_post.html.erb
<!-- HTML TAGS:
<div> defines a division or a section;
<p> defines a paragraph;
<span> is used to color a part of text. 
-->

<div class = "row">
  <div class = "col-md-6 well">
  <!-- Show tags-->
  <%= render partial: "tags/tag", collection: post.tags %>
  <!-- Show posts-->   
    <p>
    <h3><%= post.topic %></h3>
    </p>
    <span>
    <%= link_to "See More", post_path(post)%>
    </span>
  </div>
</div>

app/views/posts/index.html.erb
<%= render 'shared/title', title: "Posts" %>

<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/new.html.erb
<%= render "shared/title", title: "Say Something!" %>

<div class = "row">
  <div class = "col-md-6 well">
<!-- Use form helper -->
    <%= form_for Post.new do |f| %>
<!-- Topic -->
      <div class = "form-group">
        <%= f.label :topic %>
        <br>
        <%= f.text_field :topic %>
      </div>

<!-- Post_text -->
      <div class = "form-group">
        <%= f.label :post_text %>
        <br>
        <%= f.text_area :post_text, size: "50x10" %>
      </div>

<!-- Tags -->
      <div class="form-group">
      <%= f.label :tags %>
      <br>
      <%= collection_check_boxes(:post, :tag_ids, Tag.all, :id, :tag_title) do |cbox|%>
      <%= cbox.label(class: "checkbox-inline") { cbox.check_box(class: "checkbox") + cbox.text } %>
      <% end %>
    </div>

<!-- Submit button -->
      <br>
      <%= f.submit(@post.new_record? ? "Submit" : "Update Post", class: "btn btn-primary") %>
    <% end %>
  </div>
</div>

<!-- Link to the main page -->
<hr>

<%= link_to "Back", posts_path%>

app/views/posts/show.html.erb
<!-- Show a post-->
<%= render 'shared/title', title: "You are reading: #{@post.topic}" %>

<div class = "row">
  <div class = "col-md-6 well">
<!-- Show tags-->
    <%= render partial: "tags/tag", collection: @post.tags %>
    <p>
      <h3><%= @post.topic%></h3>
    </p>
    <br>
    <p>
      <%= @post.post_text%>
    </p>
    <br>
      <small> Posted by </small><%= "#{@post.user.name}" %>
  </div>
</div>

<!-- Show comments of a post-->
<h3>Comments:</h3>

<% @post.comments.each do |comment| %>
  <div class = "row">
    <div class = "col-md-6 well">
      <p>
      	<%= comment.comment_text %>
      </p>
      <br>
        <small> Commented by </small><%= "#{comment.user.name}" %>
    </div>
  </div>
<% end %>

<!-- User only -->
<% if logged_in? %>
<!-- Create a new comment -->
  <h3>Leave your comments here!</h3>

  <%= form_for [@post, @comment] do |f| %>
    <div class = "row">
      <%= f.text_area :comment_text, rows: 3, class: "col-md-6" %>
      <div class = "col-md-6">
        <%= f.submit "Submit", class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>

<% end %>

<!-- Link to the main page -->
<hr>

<div class = "row">
  <%= link_to "Back", posts_path%>
</div>

app/views/shared/_title.html.erb
<h2><%= title %></h2>
</hr>

app/views/tags/_tag.html.erb
<% if tag.tag_title == "Poll" %>
  <span class = "badge alert-danger">

<% elsif tag.tag_title == "Discussion" %>
  <span class = "badge alert-success">

<% elsif tag.tag_title == "Chat" %>
  <span class = "badge progress-bar-info">

<% elsif tag.tag_title == "Gossip" %>
  <span class = "badge progress-bar-warning">

<% elsif tag.tag_title == "Question" %>
  <span class = "badge progress-bar-primary">

<% elsif tag.tag_title == "Hate!" %>
  <span class = "badge alert-danger">

<% end %>
  <%= tag.tag_title %>
</span>

<!--
Tag.create(tag_title: "Poll")
Tag.create(tag_title: "Discussion")
Tag.create(tag_title: "Chat")
Tag.create(tag_title: "Gossip")
Tag.create(tag_title: "Question")
Tag.create(tag_title: "Hate!")
-->

app/views/tags/index.html.erb
<%= render "shared/title", title: "Tags" %>

<% @tags.each do |tag| %>
<div class = "row">
  <div class = "col-md-6 well">
      <p> <b><%= tag.tag_title %></p>
  </div>
</div>
<% end %>

app/views/tags/new.html.erb
<%= render "shared/title", title: "Create New Tags" %>

<div class = "row">
  <div class = "col-md-6 well">
<!-- Use form helper -->
    <%= form_for @tag do |t| %>
<!-- Topic -->
      <div class = "form-group">
        <%= t.label :tag_title %>
        <br>
        <%= t.text_field :tag_title %>
      </div>

<!-- Submit button -->
      <%= t.submit "Create", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<!-- Link to the main page -->
<hr>

<%= link_to "Back", posts_path%>

app/views/users/new.html.erb
<%= render 'shared/title', title: "Please Register" %>

<div class = "row">
  <div class = "col-md-6 well">
<!-- Use form helper -->
    <%= form_for @user do |f| %>
<!-- Topic -->
      <div class = "form-group">
      <%= f.label :name %>
      <br>
      <%= f.text_field :name %>
      </div>

<!-- Post_text -->
      <div class = "form-group">
      <%= f.label :password %>
      <br>
      <%= f.text_field :password %>
      </div>

<!-- Submit button -->
    <%= f.submit(@user.new_record? ? "Register" : "Update Profile", class: "btn btn-info") %>
    <% end %>
  </div>
</div>

<!-- Link to the main page -->
<hr>

<%= link_to "Not Now", posts_path%>

app/views/users/show.html.erb
<%= render 'shared/title', title: "#{@user.name}" %>

<!-- Show the user's posts -->
<br>
<h3>Posts</h3>

<% @user.posts.each do |post|%>
  <div class = "row">
    <div class = "col-md-6 well">
      <%= render partial: "tags/tag", collection: post.tags %>
      <p>
      <h3><%= post.topic %></h3>
      <p>
        <%= post.post_text%>
      </p>
    </div>
  </div>
<% end %>

<!-- Show the user's comments -->
<br>
<h3>Comments</h3>

<% @user.comments.each do |comment|%>
  <div class = "row">
    <div class = "col-md-6 well">
      <p>
        <%= comment.comment_text %>
      </p>
    </div>
  </div>
<% end %>

<!-- Link to the main page -->
<hr>

<div class = "row">
  <%= link_to "Back", posts_path%>
</div>